### ISSUE TITLE
How to export multilocus lineages data (including only one individual from the particular MLL) to genalex file with poppr

### ISSUE THREAD

**Issue by Hoaran** [grunwaldlab/poppr#209] opened 2019-09-11 00:21 UTC
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [X] I have the most recent version of poppr and R
 - [ ] I have found a bug
   - [X] I have searched for solutions on this site and the [poppr forum](https://groups.google.com/group/poppr)
   - [ ] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [X] I want to request a new feature

--------
Dear Zhian,

I'm Learning how to use poppr R package, and I want to know how to export multilocus lineages data with poppr. In order to make the genetic diversity and genetic structure analyses performed in Arlequin and Structure program at the genet level that is, including only one individual from the particular MLL.
Looking forward to your reply！

Best wishes，
Haoran

```r
# insert reprex here
```

---------

**Comment by zkamvar** [comment] 2019-09-11 07:18
This is a duplicate of a question asked on the forum. Please do not do this.

**Closed by zkamvar** 2019-09-11 07:18 UTC
